// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChZZV9rnY2ympWx_hq-QX-8IgoI3L7m2g',
    appId: '1:402262511810:web:5248c09ccc5ee3cc51eb5b',
    messagingSenderId: '402262511810',
    projectId: 'taskapp-acaf7',
    authDomain: 'taskapp-acaf7.firebaseapp.com',
    storageBucket: 'taskapp-acaf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDAtCTU00ssxARgorgqlBej_4nHpJnIvA',
    appId: '1:402262511810:android:002ae60858e7d3f351eb5b',
    messagingSenderId: '402262511810',
    projectId: 'taskapp-acaf7',
    storageBucket: 'taskapp-acaf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvOUy0tT4V9pJPCOgllZnuT4DjTulsMno',
    appId: '1:402262511810:ios:4041472463aed97f51eb5b',
    messagingSenderId: '402262511810',
    projectId: 'taskapp-acaf7',
    storageBucket: 'taskapp-acaf7.appspot.com',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvOUy0tT4V9pJPCOgllZnuT4DjTulsMno',
    appId: '1:402262511810:ios:6dcbb09bb12a239751eb5b',
    messagingSenderId: '402262511810',
    projectId: 'taskapp-acaf7',
    storageBucket: 'taskapp-acaf7.appspot.com',
    iosBundleId: 'com.example.taskapp.RunnerTests',
  );
}
